version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ${USERPROFILE}\.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=us-east-1  # Tu región
    networks:
      - upbib_network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upbib
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./app/scripts_sql:/docker-entrypoint-initdb.d
    networks:
      - upbib_network
networks:
  upbib_network:
    driver: bridge