version: '3.8'
services:
#  frontend:
#    build:
#      context: ./front
#      dockerfile: Dockerfile.frontend
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./front:/app
#      - /app/node_modules
#    environment:
#      - NODE_ENV=development
#    networks:
#      - upbib_network
#
#  backend:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#      - ${USERPROFILE}\.aws:/root/.aws:ro
#    environment:
#      - AWS_PROFILE=default
#      - AWS_REGION=us-east-1
#    networks:
#      - upbib_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upbib
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./app/scripts_sql:/docker-entrypoint-initdb.d